name: haskell-artificial-neural-net
version: 0.1.0.0
synopsis: Implementation of an artificial neural net and the perceptron algorithm in haskell.
maintainer: Arne Winter
github: arnemileswinter/haskell-artificial-neural-net
category: Development

dependencies:
  - base >= 4.7 && < 5
  - random

ghc-options: -Wall -threaded -O2

library:
  exposed-modules:
    - ML.NeuralNet
    - ML.Perceptron
    - Util.MonadRandom
  source-dirs: 
    - src

executables:
  xor:
    main: XOR.hs
    source-dirs: app/xor
    dependencies:
      - haskell-artificial-neural-net
  mnist:
    main: MNist.hs
    source-dirs: app/mnist
    dependencies:
      - haskell-artificial-neural-net
      - binary
      - bytestring
      - filepath
